apiVersion: v1
kind: ServiceAccount
metadata: { name: payment-operator }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: payment-router }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: participant-payment-manager }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: participant-admin }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: operator-db }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: router-db }
---
apiVersion: v1
kind: ServiceAccount
metadata: { name: participant-db }
