apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: payment-operator
    newName: payment-operator
    newTag: dev
  - name: payment-router
    newName: payment-router
    newTag: dev
  - name: payment-participant-manager
    newName: payment-participant-manager
    newTag: dev
