apiVersion: 1
providers:
  - name: payment-mesh
    orgId: 1
    folder: Payment Mesh
    type: file
    disableDeletion: true
    allowUiUpdates: false
    updateIntervalSeconds: 10
    options:
      path: /var/lib/grafana/dashboards
